# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tom Looman
subtitle: Unreal Engine Tutorials
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: t_looman
github_username:  tomlooman
logo: "/assets/site_logo_whiteorange.webp"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from


search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true

# SEO Related
google_site_verification : "" # Replace this with your ID, or delete

include:
  - _pages
#exclude:
#  - runlocal
#exclude:
#  - /react_src/src/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      css: main
  # courses
  - scope:
      path: "_pages/courses"
      type: pages
    values:
      layout: single
      css: main
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      css: main
      toc: true
      toc_sticky: true
      related: true
      read_time: false
      share: false
      permalink: /:title/
      sidebar:
        nav: "sidebar-main"
  # _nuggets
  - scope:
      path: "_nuggets"
    values:
      layout: single
      css: main



collections:
  nuggets:
    output: true
    permalink: /:collection/:name


analytics:
  provider: custom


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
